my_robot_new_station_giskard:
  ros__parameters:
    name: "giskard"

my_robot_new_station_bb8:
  ros__parameters:
    name: "bb8"

my_robot_new_station_daneel:
  ros__parameters:
    name: "daneel"

my_robot_new_station_jander:
  ros__parameters:
    name: "jander"

my_robot_new_station_c3po:
  ros__parameters:
    name: "c3po"